# Generated by Django 3.0.4 on 2020-03-31 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_ocrimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocrimage',
            name='text',
            field=models.TextField(),
        ),
    ]
